package application.stats;

public enum Item {
  BoxingGloves,
  PlasmaCore,
  SatelliteTurrets,
  Anvil,
  InflatableBalloon,
  AttackNeedles,
  Hellfire,
  DynamiteStick,
  Pinball,
  Notebook,
  Adrenaline,
  SpiritMagnet,
  MetalDetector,
  EnergyDrink,
  AncientScripture,
  BloodyMirror,
  SpiritSeeker,
  BraveFeather,
  Shiruken,
  DangerReflex,
  DoubleShot,
  TripleShot,
  Shotgun,
  Overclock,
  TruePrecision,
  Delineator,
  RainStorm
}
